# Generated by Django 2.0.5 on 2018-06-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharedNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.notes')),
            ],
        ),
    ]
